openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: REST API для керування контактами з авторизацією, email та зображеннями

tags:
  - name: Auth
    description: Authentication operations
  - name: Contacts
    description: Contact management

servers:
  - url: https://nodejs-hw-mw7-swagger-1-lacz.onrender.com

paths:
  /auth/register:
    post:
      $ref: '../swagger/paths/auth/register.yaml'
  /auth/login:
    post:
      $ref: '../swagger/paths/auth/login.yaml'
  /auth/logout:
    post:
      $ref: '../swagger/paths/auth/logout.yaml'
  /auth/current:
    get:
      $ref: '../swagger/paths/auth/current.yaml'
  /auth/refresh:
    post:
      $ref: '../swagger/paths/auth/refresh.yaml'
  /contacts:
    get:
      $ref: '../swagger/paths/contacts/get.yaml'
    post:
      $ref: '../swagger/paths/contacts/post.yaml'
  /contacts/{id}:
    get:
      $ref: '../swagger/paths/contacts/{id}/get.yaml'
    patch:
      $ref: '../swagger/paths/contacts/{id}/patch.yaml'
    delete:
      $ref: '../swagger/paths/contacts/{id}/delete.yaml'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Contact:
      $ref: '../swagger/components/schemas/Contact.yaml'
    ContactInput:
      $ref: '../swagger/components/schemas/ContactInput.yaml'
    Error:
      $ref: '../swagger/components/schemas/Error.yaml'
