openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts app
  license:
    name: ISC
    identifier: ISC
  description: This is a documentation of contacts app
tags:
  - name: Contacts
    description: Contacts operations.
  - name: Auth
    description: Auth operations.
servers:
  - url: http://localhost:3000
  - url: https://nodejs-hw-mongodb-1-lacz.onrender.com
paths:
  /contacts:
    get:
      $ref: ../swagger/paths/contacts/get.yaml
    post:
      $ref: ../swagger/paths/contacts/post.yaml
  /contacts/{contactId}:
    get:
      $ref: ../swagger/paths/contacts/{contactId}/get.yaml
    put:
      $ref: ../swagger/paths/contacts/{contactId}/put.yaml
    patch:
      $ref: ../swagger/paths/contacts/{contactId}/patch.yaml
    delete:
      $ref: ../swagger/paths/contacts/{contactId}/delete.yaml
  /auth/register:
    post:
      $ref: ../swagger/paths/auth/register.yaml
  /auth/login:
    post:
      $ref: ../swagger/paths/auth/login.yaml
  /auth/refresh:
    post:
      $ref: ../swagger/paths/auth/refresh.yaml
  /auth/logout:
    post:
      $ref: ../swagger/paths/auth/logout.yaml
  /auth/send-reset-email:
    post:
      $ref: ../swagger/paths/auth/send-reset-email.yaml
  /auth/reset-pwd:
    post:
      $ref: ../swagger/paths/auth/reset-pwd.yaml

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
